name: Selenium Test Automation
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run every Morning 7 Am
    - cron: "30 1 * * *"
  workflow_dispatch: # allow manual trigger too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests with Gradle
        run: ./gradlew clean test --stacktrace || true

      - name: Upload TestNG Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: build/reports/tests/test
          if-no-files-found: ignore